Users can now reply to comments.
**Small description:**
The blog structure is as follows:
A user can publish an article. Other users can comment on the article. Users can reply to a comment.

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -31,6 +31,14 @@ if [ $? -ne 0 ]; then
  exit 1
 fi
 
+#Run ESLint
+echo "${green}[JavaScript Style][Info]: Checking JavaScript Style${NC}"
+eslint app/javascript/**
+if [ $? -ne 0 ]; then
+ echo "${red}[JavaScript Style][Error]: Fix the issues and commit again${NC}"
+ exit 1
+fi
+
 # Run Specs
 # echo "${green}[RSpec][Info]: Checking Rspec tests${NC}"
 # bin/bundle exec rspec spec
